// output.cpp
// Output object representing the output file (body file) generated by the simulation

#include "output.h"
#include "body.h"
#include "units.h"
#include "misc.h"
#include "linkedlist.h"

#include <fstream>

using namespace std;

Output::Output(string _fileName) {
	// Constructor - set the fileName for the output file
	fileName = _fileName;
	fileContents = "";
}

void Output::AddBody(Body * body) {
	// Add the parameters of a body to the output file (in standard form)
	fileContents += ToStandardForm( body->GetX() ) + ",";
	fileContents += ToStandardForm( body->GetY() ) + ",";
	fileContents += ToStandardForm( body->GetZ() ) + ",";
	fileContents += ToStandardForm( body->GetMass() ) + ",";
	fileContents += ToStandardForm( body->GetRadius() ) + ",";
	fileContents += ToStandardForm( body->GetXVelocity() ) + ",";
	fileContents += ToStandardForm( body->GetYVelocity() ) + ",";
	fileContents += ToStandardForm( body->GetZVelocity() ) + "\n";
}

void Output::Save() {
	// Write the output file to disk
	ofstream outputFile(fileName, ios::out);
	outputFile << fileContents;
	outputFile.close();
}

void Output::AddAllBodies(List bodyList) {
	// Iterate through the bodyList and add the parameters for each body to the output
	Body * body = bodyList.GetHead();

	while (body != NULL) {
		AddBody(body);
		body = body->GetNext();
	}
}
