// output.h
// Output object representing the output file (body file) generated by the simulation

#ifndef __OUTPUT_H_INCLUDED__
#define __OUTPUT_H_INCLUDED__

#include <iostream>

#include "body.h"
#include "linkedlist.h"

using namespace std;

class Output {
		string file_name;
		string file_contents;

	public:
		Output(string _file_name);

		void AddBody(Body * body);
		void AddAllBodies(List body_list);
		void AddParameters(int step_number, double dt, double time_elapsed, int body_count);
		void Save();
};

#endif
