// output.h
// Output object representing the output file (body file) generated by the simulation

#ifndef __OUTPUT_H_INCLUDED__
#define __OUTPUT_H_INCLUDED__

#include <iostream>

#include "body.h"
#include "linkedlist.h"

using namespace std;

class Output {
		string fileName;
		string fileContents;

	public:
		Output(string _fileName);

		void AddBody(Body * body);
		void AddAllBodies(List bodyList);
		void Save();
};

#endif
